---
kind: ServiceAccount
apiVersion: v1
metadata:
  creationTimestamp: null
  labels:
    app: {{ print "sa-build-" .Values.name  | quote }}
  name: {{ print "sa-build-" .Values.name  | quote }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  creationTimestamp: null
  labels:
    app: {{ printf "sa-tag-%s" .Values.name | quote }}
  name: {{ printf "sa-tag-%s" .Values.name | quote }}